name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [tests, release]
        default: tests
        description: Only run tests or release a new version to PyPI after tests pass.

jobs:
  test:
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/requirements.txt'
      - name: Install dependencies
        run: |
          pip install --quiet -r requirements.txt -r requirements-ci.txt
          pip install -e .
      - name: pytest
        run: |
          pytest --cov=usatt tests --color=yes
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    if: github.event.name == 'release'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      # For pypi trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10"
      - run: |
          python -m pip install build
          pip install -e .
          pip wheel -w dist .
      - name: Build sdist
        run: python -m build --sdist
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
